In [3]:
%config IPCompleter.greedy=True

In [4]:
import os
import chardet
import petl as etl
import glob
import pickle
import re
import uuid
import sys
import pandas as pd
import io
import csv
import datetime
import json

from azure.storage.blob import ContainerClient,BlobServiceClient, BlobClient,PublicAccess, BlobBlock
from azure.storage.file import FileService

## Conex√£o Blob

In [5]:
container = ContainerClient (account_url = f"https://datalake2transient.blob.core.windows.net/",
                                       credential = 'wlxJHcWvtVhPpL/zs6l+F1bJGKZnJ4HppZcVyh+ns32oH46E3dY/HBLau3V6um9hv+KZf/3mXEAL5nHD41X3jg==', container_name = 'datalake2dictas')

## Conn Blob

In [6]:
account_name='datalake2dictas'
account_key='wlxJHcWvtVhPpL/zs6l+F1bJGKZnJ4HppZcVyh+ns32oH46E3dY/HBLau3V6um9hv+KZf/3mXEAL5nHD41X3jg=='
container_from = 'transient'
container_to = 'raw'

In [7]:
cc_transient = ContainerClient(account_url=f"https://{account_name}.blob.core.windows.net/",container_name=container_from, credential=account_key)
cc_raw = ContainerClient(account_url=f"https://{account_name}.blob.core.windows.net/",container_name=container_to, credential=account_key)
cc_trusted = ContainerClient(account_url=f"https://{account_name}.blob.core.windows.net/",container_name='trusted', credential=account_key)
cc_refined = ContainerClient(account_url=f"https://{account_name}.blob.core.windows.net/",container_name='refined', credential=account_key)

In [8]:
# List the blobs in the container.
print("\nList blobs in the container")
blob_list = cc_transient.list_blobs()
for blob in blob_list:
    print(blob.name + '\n')

List blobs in the container
beneficiario/BENEFICIARIOS.csv

consultas/CONSULTAS.csv

custo/CUSTO 012018.csv

custo/CUSTO 012019.csv

custo/CUSTO 022017.csv

custo/CUSTO 022018.csv

custo/CUSTO 022019.csv

custo/CUSTO 032017.csv

custo/CUSTO 032018.csv

custo/CUSTO 032019.csv

custo/CUSTO 042017.csv

custo/CUSTO 042018.csv

custo/CUSTO 042019.csv

custo/CUSTO 052017.csv

custo/CUSTO 052018.csv

custo/CUSTO 052019.csv

custo/CUSTO 062017.csv

custo/CUSTO 062018.csv

custo/CUSTO 062019.csv

custo/CUSTO 072017.csv

custo/CUSTO 072018.csv

custo/CUSTO 072019.csv

custo/CUSTO 082017.csv

custo/CUSTO 082018.csv

custo/CUSTO 082019.csv

custo/CUSTO 092017.csv

custo/CUSTO 092018.csv

custo/CUSTO 092019.csv

custo/CUSTO 102017.csv

custo/CUSTO 102018.csv

custo/CUSTO 112017.csv

custo/CUSTO 112018.csv

custo/CUSTO 122017.csv

custo/CUSTO 122018.csv

diarias/DIARIAS.csv

empresa/EMPRESA.csv

prestador/PRESTADORES.csv

receitas/RECEITA 012018.csv

receitas/RECEITA 012019.csv

receitas/RECEITA 022017.csv

receitas/RECEITA 022018.csv

receitas/RECEITA 022019.csv

receitas/RECEITA 032017.csv

receitas/RECEITA 032018.csv

receitas/RECEITA 032019.csv

receitas/RECEITA 042017.csv

receitas/RECEITA 042018.csv

receitas/RECEITA 042019.csv

receitas/RECEITA 052017.csv

receitas/RECEITA 052018.csv

receitas/RECEITA 052019.csv

receitas/RECEITA 062017.csv

receitas/RECEITA 062018.csv

receitas/RECEITA 062019.csv

receitas/RECEITA 072017.csv

receitas/RECEITA 072018.csv

receitas/RECEITA 072019.csv

receitas/RECEITA 082017.csv

receitas/RECEITA 082018.csv

receitas/RECEITA 082019.csv

receitas/RECEITA 092017.csv

receitas/RECEITA 092018.csv

receitas/RECEITA 092019.csv

receitas/RECEITA 102017.csv

receitas/RECEITA 102018.csv

receitas/RECEITA 102019.csv

receitas/RECEITA 112017.csv

receitas/RECEITA 112018.csv

receitas/RECEITA 122017.csv

receitas/RECEITA 122018.csv

servico/SERVICOS.csv

vidas/VIDAS 012018.csv

vidas/VIDAS 012019.csv

vidas/VIDAS 02-2017.csv

vidas/VIDAS 022018.csv

vidas/VIDAS 022019.csv

vidas/VIDAS 032017.csv

vidas/VIDAS 032018.csv

vidas/VIDAS 032019.csv

vidas/VIDAS 042017.csv

vidas/VIDAS 042018.csv

vidas/VIDAS 042019.csv

vidas/VIDAS 052017.csv

vidas/VIDAS 052018.csv

vidas/VIDAS 052019.csv

vidas/VIDAS 062017.csv

vidas/VIDAS 062018.csv

vidas/VIDAS 062019.csv

vidas/VIDAS 072017.csv

vidas/VIDAS 072018.csv

vidas/VIDAS 072019.csv

vidas/VIDAS 082017.csv

vidas/VIDAS 082018.csv

vidas/VIDAS 082019.csv

vidas/VIDAS 092017.csv

vidas/VIDAS 092018.csv

vidas/VIDAS 092019.csv

vidas/VIDAS 102017.csv

vidas/VIDAS 102018.csv

vidas/VIDAS 102019.csv

vidas/VIDAS 112017.csv

vidas/VIDAS 112018.csv

vidas/VIDAS 122017.csv

vidas/VIDAS 122018.csv

In [9]:
notebook_dir = '/home/giovani/Documentos/jupyter/erros'

In [126]:
blob_dir = 'beneficiario'
blob_file = 'BENEFICIARIOS.csv'
csv_file = 'RECEITA 012018_error.csv'

with open(f'{notebook_dir}/{blob_file}','wb') as data_from:
    data_from.write(cc_trusted.get_blob_client(f'{blob_dir}/{blob_file}').download_blob().readall())
    
#df = pd.read_pickle(f'{notebook_dir}/{blob_file}')

In [127]:
df = pd.read_pickle(f'{notebook_dir}/{blob_file}')   
df

,mes_competencia,fk_beneficiario,fk_empresa,dt_geracao_titulo,tipo_cobranca,vl_cobranca,vl_pago,validate,inf_val
0,12018,354000129,16539926000190,,CONT,949.09,949.09,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."
1,12018,354000129,16539926000190,,PART,30.71,30.71,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."
2,12018,428000157,16539926000190,,PART,630.48,630.48,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."
3,12018,551000210,16539926000190,,PART,185.96,185.96,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."
4,12018,50000015,3907799000192,,CONT,384.14,384.14,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."
...,...,...,...,...,...,...,...,...,...
184321,12018,10371003055,17155730000164,,PART,630.48,630.48,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."
184322,12018,10371003055,17155730000164,,PART,134.48,134.48,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."
184323,12018,10404003072,17155730000164,,PART,4.61,4.61,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."
184324,12018,10409003073,17155730000164,,CONT,220.17,220.17,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."
184325,12018,12442004028,17155730000164,,PART,7.22,7.22,False,"[{'mes_competencia': True}, {'fk_beneficiario'..."

In [128]:
dfcsv=df.to_csv(f'{notebook_dir}/{csv_file}')

## Teste de cast

In [131]:
str_date = '20200220'
date = datetime.strptime(str_date, '%Y%m%d').date()
)

datetime.date(2020, 2, 20)

In [141]:
str_date = '20200220'
dt = datetime.datetime.strptime(str_date, '%Y%m%d')
data = '{0}/{1:02d}/{2}'.format(dt.day, dt.month, dt.year)
data

'20/02/2020'

In [142]:
str_date = '20200220'
dt = datetime.datetime.strptime(str_date, '%Y%m%d')
print('{0}/{1:02d}/{2}'.format(dt.day, dt.month, dt.year))

20/02/2020

In [143]:
def cast_date(str_date):
    dt = datetime.datetime.strptime(str_date, '%Y%m%d')
    data = '{0}/{1:02d}/{2}'.format(dt.day, dt.month, dt.year)
    return data

In [144]:
cast_str = cast_date(str_date)
cast_str

'20/02/2020'